---
- name: Install Wordpress
  become: yes 
  become_method: sudo
  user: centos
  hosts: all
  tasks:
   - name: Download  wordpress
     get_url:
       url: https://wordpress.org/latest.tar.gz 
       dest: /tmp/latest.tar.gz
   - name: Unzip wordpress
     unarchive: 
        src: /tmp/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes 
   - name: Move files to html folder
     shell: "mv /var/www/html/wordpress/*  /var/www/html"
     ignore_errors: yes
   - name: Restart httpd
     systemd:
        name: httpd
        state: restarted  
        enabled: yes
      