---
- name: Install Wordpress
  hosts: localhost
  become: yes 
  become_method: sudo
  tasks:
   - name: Download and unzip wordpress
     get_url:
       url: https://wordpress.org/latest.tar.gz 
       dest: /tmp/
   - name: Unzip wordpress
     unarchive: 
        src: /tmp/latest.tar.gz
        dest: /var/www/html/
        remote_src: yes 

   - name: Move files to html folder
     shell: "mv wordpress/*  /var/www/html"
     become: yes
     become_method: sudo
     ignore_errors: yes
  