---
- name: Installs  Packages
  become: yes 
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: Install Items
    package:
      name: "{{item}}"
      state: latest 
    with_items: 
    - httpd
    - epel-release 
    - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
    - mysql
    - mariadb-server
    - php-gd 
    - php
    - php-mysql
    - wget
  ignore_errors: yes

