---
  become: yes 
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: Install users
    package:
      name: "{{item}}"
      state: present
    with_items: 
    - bob
    - liza
    - mike
    - sara