---
- name: User Playbook
  become: yes 
  become_method: sudo
  user: centos
  hosts: all
  tasks:
  - name: Add user Bob
    user:
      name: bob
      comment: "John Smith"
      groups: wheel
      generate_ssh_key: yes 
      state: present

  - name: Add user Lisa
    user:
      name: bob
      state: absent